/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

module sdram_controller(clk, reset, address, read_request, ready, req_ack, activate_cmd, precharge_cmd, read_cmd, bank_cmd, row_cmd, column_cmd, init_done, precharge_all_cmd, refresh_cmd, load_mode_cmd, data_valid, read_data);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  output activate_cmd;
  wire activate_cmd;
  input [23:0] address;
  wire [23:0] address;
  output [1:0] bank_cmd;
  wire [1:0] bank_cmd;
  input clk;
  wire clk;
  output [7:0] column_cmd;
  wire [7:0] column_cmd;
  output data_valid;
  wire data_valid;
  output init_done;
  wire init_done;
  output load_mode_cmd;
  wire load_mode_cmd;
  output precharge_all_cmd;
  wire precharge_all_cmd;
  output precharge_cmd;
  wire precharge_cmd;
  output read_cmd;
  wire read_cmd;
  output [31:0] read_data;
  wire [31:0] read_data;
  input read_request;
  wire read_request;
  output ready;
  wire ready;
  output refresh_cmd;
  wire refresh_cmd;
  output req_ack;
  wire req_ack;
  input reset;
  wire reset;
  output [11:0] row_cmd;
  wire [11:0] row_cmd;
  wire \u_bank_manager.active_row_reg[0][0] ;
  wire \u_bank_manager.active_row_reg[0][10] ;
  wire \u_bank_manager.active_row_reg[0][11] ;
  wire \u_bank_manager.active_row_reg[0][1] ;
  wire \u_bank_manager.active_row_reg[0][2] ;
  wire \u_bank_manager.active_row_reg[0][3] ;
  wire \u_bank_manager.active_row_reg[0][4] ;
  wire \u_bank_manager.active_row_reg[0][5] ;
  wire \u_bank_manager.active_row_reg[0][6] ;
  wire \u_bank_manager.active_row_reg[0][7] ;
  wire \u_bank_manager.active_row_reg[0][8] ;
  wire \u_bank_manager.active_row_reg[0][9] ;
  wire \u_bank_manager.active_row_reg[1][0] ;
  wire \u_bank_manager.active_row_reg[1][10] ;
  wire \u_bank_manager.active_row_reg[1][11] ;
  wire \u_bank_manager.active_row_reg[1][1] ;
  wire \u_bank_manager.active_row_reg[1][2] ;
  wire \u_bank_manager.active_row_reg[1][3] ;
  wire \u_bank_manager.active_row_reg[1][4] ;
  wire \u_bank_manager.active_row_reg[1][5] ;
  wire \u_bank_manager.active_row_reg[1][6] ;
  wire \u_bank_manager.active_row_reg[1][7] ;
  wire \u_bank_manager.active_row_reg[1][8] ;
  wire \u_bank_manager.active_row_reg[1][9] ;
  wire \u_bank_manager.active_row_reg[2][0] ;
  wire \u_bank_manager.active_row_reg[2][10] ;
  wire \u_bank_manager.active_row_reg[2][11] ;
  wire \u_bank_manager.active_row_reg[2][1] ;
  wire \u_bank_manager.active_row_reg[2][2] ;
  wire \u_bank_manager.active_row_reg[2][3] ;
  wire \u_bank_manager.active_row_reg[2][4] ;
  wire \u_bank_manager.active_row_reg[2][5] ;
  wire \u_bank_manager.active_row_reg[2][6] ;
  wire \u_bank_manager.active_row_reg[2][7] ;
  wire \u_bank_manager.active_row_reg[2][8] ;
  wire \u_bank_manager.active_row_reg[2][9] ;
  wire \u_bank_manager.active_row_reg[3][0] ;
  wire \u_bank_manager.active_row_reg[3][10] ;
  wire \u_bank_manager.active_row_reg[3][11] ;
  wire \u_bank_manager.active_row_reg[3][1] ;
  wire \u_bank_manager.active_row_reg[3][2] ;
  wire \u_bank_manager.active_row_reg[3][3] ;
  wire \u_bank_manager.active_row_reg[3][4] ;
  wire \u_bank_manager.active_row_reg[3][5] ;
  wire \u_bank_manager.active_row_reg[3][6] ;
  wire \u_bank_manager.active_row_reg[3][7] ;
  wire \u_bank_manager.active_row_reg[3][8] ;
  wire \u_bank_manager.active_row_reg[3][9] ;
  wire \u_bank_manager.bank_open_reg[0] ;
  wire \u_bank_manager.bank_open_reg[1] ;
  wire \u_bank_manager.bank_open_reg[2] ;
  wire \u_bank_manager.bank_open_reg[3] ;
  wire \u_bank_manager.query_bank[0] ;
  wire \u_bank_manager.query_bank[1] ;
  wire \u_command_generator.delay_counter[0] ;
  wire \u_command_generator.delay_counter[1] ;
  wire \u_command_generator.delay_counter[2] ;
  wire \u_command_generator.delay_counter[3] ;
  wire \u_command_generator.precharge_for_miss ;
  wire \u_command_generator.req_pending ;
  wire \u_command_generator.request_column_reg[0] ;
  wire \u_command_generator.request_column_reg[1] ;
  wire \u_command_generator.request_column_reg[2] ;
  wire \u_command_generator.request_column_reg[3] ;
  wire \u_command_generator.request_column_reg[4] ;
  wire \u_command_generator.request_column_reg[5] ;
  wire \u_command_generator.request_column_reg[6] ;
  wire \u_command_generator.request_column_reg[7] ;
  wire \u_command_generator.request_row_reg[0] ;
  wire \u_command_generator.request_row_reg[10] ;
  wire \u_command_generator.request_row_reg[11] ;
  wire \u_command_generator.request_row_reg[1] ;
  wire \u_command_generator.request_row_reg[2] ;
  wire \u_command_generator.request_row_reg[3] ;
  wire \u_command_generator.request_row_reg[4] ;
  wire \u_command_generator.request_row_reg[5] ;
  wire \u_command_generator.request_row_reg[6] ;
  wire \u_command_generator.request_row_reg[7] ;
  wire \u_command_generator.request_row_reg[8] ;
  wire \u_command_generator.request_row_reg[9] ;
  wire \u_command_generator.state[0] ;
  wire \u_command_generator.state[1] ;
  wire \u_command_generator.state[5] ;
  wire \u_command_generator.state[6] ;
  wire \u_command_generator.state[7] ;
  wire \u_sdram_init.delay_counter[0] ;
  wire \u_sdram_init.delay_counter[10] ;
  wire \u_sdram_init.delay_counter[11] ;
  wire \u_sdram_init.delay_counter[12] ;
  wire \u_sdram_init.delay_counter[13] ;
  wire \u_sdram_init.delay_counter[14] ;
  wire \u_sdram_init.delay_counter[15] ;
  wire \u_sdram_init.delay_counter[1] ;
  wire \u_sdram_init.delay_counter[2] ;
  wire \u_sdram_init.delay_counter[3] ;
  wire \u_sdram_init.delay_counter[4] ;
  wire \u_sdram_init.delay_counter[5] ;
  wire \u_sdram_init.delay_counter[6] ;
  wire \u_sdram_init.delay_counter[7] ;
  wire \u_sdram_init.delay_counter[8] ;
  wire \u_sdram_init.delay_counter[9] ;
  wire \u_sdram_init.state[0] ;
  wire \u_sdram_init.state[1] ;
  wire \u_sdram_init.state[2] ;
  sky130_fd_sc_hd__and3b_2 _366_ (
    .A_N(\u_command_generator.req_pending ),
    .B(\u_command_generator.state[0] ),
    .C(read_request),
    .X(_115_)
  );
  sky130_fd_sc_hd__buf_1 _367_ (
    .A(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__buf_1 _368_ (
    .A(_116_),
    .X(req_ack)
  );
  sky130_fd_sc_hd__inv_2 _369_ (
    .A(data_valid),
    .Y(_117_)
  );
  sky130_fd_sc_hd__buf_1 _370_ (
    .A(_000_),
    .X(_118_)
  );
  sky130_fd_sc_hd__buf_1 _371_ (
    .A(_001_),
    .X(_119_)
  );
  sky130_fd_sc_hd__mux4_2 _372_ (
    .A0(\u_bank_manager.active_row_reg[0][1] ),
    .A1(\u_bank_manager.active_row_reg[1][1] ),
    .A2(\u_bank_manager.active_row_reg[2][1] ),
    .A3(\u_bank_manager.active_row_reg[3][1] ),
    .S0(_118_),
    .S1(_119_),
    .X(_120_)
  );
  sky130_fd_sc_hd__xnor2_2 _373_ (
    .A(\u_command_generator.request_row_reg[1] ),
    .B(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__mux4_2 _374_ (
    .A0(\u_bank_manager.active_row_reg[0][2] ),
    .A1(\u_bank_manager.active_row_reg[1][2] ),
    .A2(\u_bank_manager.active_row_reg[2][2] ),
    .A3(\u_bank_manager.active_row_reg[3][2] ),
    .S0(_118_),
    .S1(_119_),
    .X(_122_)
  );
  sky130_fd_sc_hd__xnor2_2 _375_ (
    .A(\u_command_generator.request_row_reg[2] ),
    .B(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__mux4_2 _376_ (
    .A0(\u_bank_manager.active_row_reg[0][0] ),
    .A1(\u_bank_manager.active_row_reg[1][0] ),
    .A2(\u_bank_manager.active_row_reg[2][0] ),
    .A3(\u_bank_manager.active_row_reg[3][0] ),
    .S0(_118_),
    .S1(_119_),
    .X(_124_)
  );
  sky130_fd_sc_hd__xnor2_2 _377_ (
    .A(\u_command_generator.request_row_reg[0] ),
    .B(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__mux4_2 _378_ (
    .A0(\u_bank_manager.active_row_reg[0][9] ),
    .A1(\u_bank_manager.active_row_reg[1][9] ),
    .A2(\u_bank_manager.active_row_reg[2][9] ),
    .A3(\u_bank_manager.active_row_reg[3][9] ),
    .S0(_118_),
    .S1(_119_),
    .X(_126_)
  );
  sky130_fd_sc_hd__xnor2_2 _379_ (
    .A(\u_command_generator.request_row_reg[9] ),
    .B(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__and4_2 _380_ (
    .A(_121_),
    .B(_123_),
    .C(_125_),
    .D(_127_),
    .X(_128_)
  );
  sky130_fd_sc_hd__mux4_2 _381_ (
    .A0(\u_bank_manager.active_row_reg[0][4] ),
    .A1(\u_bank_manager.active_row_reg[1][4] ),
    .A2(\u_bank_manager.active_row_reg[2][4] ),
    .A3(\u_bank_manager.active_row_reg[3][4] ),
    .S0(_118_),
    .S1(_119_),
    .X(_129_)
  );
  sky130_fd_sc_hd__xnor2_2 _382_ (
    .A(\u_command_generator.request_row_reg[4] ),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__mux4_2 _383_ (
    .A0(\u_bank_manager.active_row_reg[0][10] ),
    .A1(\u_bank_manager.active_row_reg[1][10] ),
    .A2(\u_bank_manager.active_row_reg[2][10] ),
    .A3(\u_bank_manager.active_row_reg[3][10] ),
    .S0(_118_),
    .S1(_119_),
    .X(_131_)
  );
  sky130_fd_sc_hd__xnor2_2 _384_ (
    .A(\u_command_generator.request_row_reg[10] ),
    .B(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__mux4_2 _385_ (
    .A0(\u_bank_manager.active_row_reg[0][5] ),
    .A1(\u_bank_manager.active_row_reg[1][5] ),
    .A2(\u_bank_manager.active_row_reg[2][5] ),
    .A3(\u_bank_manager.active_row_reg[3][5] ),
    .S0(_000_),
    .S1(_001_),
    .X(_133_)
  );
  sky130_fd_sc_hd__xnor2_2 _386_ (
    .A(\u_command_generator.request_row_reg[5] ),
    .B(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__mux4_2 _387_ (
    .A0(\u_bank_manager.active_row_reg[0][8] ),
    .A1(\u_bank_manager.active_row_reg[1][8] ),
    .A2(\u_bank_manager.active_row_reg[2][8] ),
    .A3(\u_bank_manager.active_row_reg[3][8] ),
    .S0(_000_),
    .S1(_001_),
    .X(_135_)
  );
  sky130_fd_sc_hd__xnor2_2 _388_ (
    .A(\u_command_generator.request_row_reg[8] ),
    .B(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__and4_2 _389_ (
    .A(_130_),
    .B(_132_),
    .C(_134_),
    .D(_136_),
    .X(_137_)
  );
  sky130_fd_sc_hd__mux4_2 _390_ (
    .A0(\u_bank_manager.active_row_reg[0][3] ),
    .A1(\u_bank_manager.active_row_reg[1][3] ),
    .A2(\u_bank_manager.active_row_reg[2][3] ),
    .A3(\u_bank_manager.active_row_reg[3][3] ),
    .S0(_118_),
    .S1(_119_),
    .X(_138_)
  );
  sky130_fd_sc_hd__xnor2_2 _391_ (
    .A(\u_command_generator.request_row_reg[3] ),
    .B(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__mux4_2 _392_ (
    .A0(\u_bank_manager.active_row_reg[0][11] ),
    .A1(\u_bank_manager.active_row_reg[1][11] ),
    .A2(\u_bank_manager.active_row_reg[2][11] ),
    .A3(\u_bank_manager.active_row_reg[3][11] ),
    .S0(_118_),
    .S1(_119_),
    .X(_140_)
  );
  sky130_fd_sc_hd__xnor2_2 _393_ (
    .A(\u_command_generator.request_row_reg[11] ),
    .B(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__mux4_2 _394_ (
    .A0(\u_bank_manager.active_row_reg[0][7] ),
    .A1(\u_bank_manager.active_row_reg[1][7] ),
    .A2(\u_bank_manager.active_row_reg[2][7] ),
    .A3(\u_bank_manager.active_row_reg[3][7] ),
    .S0(_118_),
    .S1(_119_),
    .X(_142_)
  );
  sky130_fd_sc_hd__xnor2_2 _395_ (
    .A(\u_command_generator.request_row_reg[7] ),
    .B(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__mux4_2 _396_ (
    .A0(\u_bank_manager.active_row_reg[0][6] ),
    .A1(\u_bank_manager.active_row_reg[1][6] ),
    .A2(\u_bank_manager.active_row_reg[2][6] ),
    .A3(\u_bank_manager.active_row_reg[3][6] ),
    .S0(_118_),
    .S1(_119_),
    .X(_144_)
  );
  sky130_fd_sc_hd__xnor2_2 _397_ (
    .A(\u_command_generator.request_row_reg[6] ),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__and4_2 _398_ (
    .A(_139_),
    .B(_141_),
    .C(_143_),
    .D(_145_),
    .X(_146_)
  );
  sky130_fd_sc_hd__mux4_2 _399_ (
    .A0(\u_bank_manager.bank_open_reg[0] ),
    .A1(\u_bank_manager.bank_open_reg[1] ),
    .A2(\u_bank_manager.bank_open_reg[2] ),
    .A3(\u_bank_manager.bank_open_reg[3] ),
    .S0(\u_bank_manager.query_bank[0] ),
    .S1(\u_bank_manager.query_bank[1] ),
    .X(_147_)
  );
  sky130_fd_sc_hd__nand2_2 _400_ (
    .A(\u_command_generator.state[5] ),
    .B(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a31o_2 _401_ (
    .A1(_128_),
    .A2(_137_),
    .A3(_146_),
    .B1(_148_),
    .X(_149_)
  );
  sky130_fd_sc_hd__buf_1 _402_ (
    .A(reset),
    .X(_150_)
  );
  sky130_fd_sc_hd__buf_1 _403_ (
    .A(_150_),
    .X(_151_)
  );
  sky130_fd_sc_hd__a21oi_2 _404_ (
    .A1(_117_),
    .A2(_149_),
    .B1(_151_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__or3_2 _405_ (
    .A(\u_command_generator.delay_counter[1] ),
    .B(\u_command_generator.delay_counter[3] ),
    .C(\u_command_generator.delay_counter[2] ),
    .X(_152_)
  );
  sky130_fd_sc_hd__buf_1 _406_ (
    .A(_152_),
    .X(_153_)
  );
  sky130_fd_sc_hd__buf_1 _407_ (
    .A(activate_cmd),
    .X(_154_)
  );
  sky130_fd_sc_hd__a21oi_2 _408_ (
    .A1(\u_command_generator.state[7] ),
    .A2(_153_),
    .B1(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_2 _409_ (
    .A(_151_),
    .B(_155_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21oi_2 _410_ (
    .A1(\u_command_generator.state[6] ),
    .A2(_153_),
    .B1(read_cmd),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2_2 _411_ (
    .A(_151_),
    .B(_156_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor3_2 _412_ (
    .A(\u_command_generator.delay_counter[1] ),
    .B(\u_command_generator.delay_counter[3] ),
    .C(\u_command_generator.delay_counter[2] ),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a22o_2 _413_ (
    .A1(\u_command_generator.state[5] ),
    .A2(_147_),
    .B1(_157_),
    .B2(\u_command_generator.state[7] ),
    .X(_158_)
  );
  sky130_fd_sc_hd__inv_2 _414_ (
    .A(reset),
    .Y(_159_)
  );
  sky130_fd_sc_hd__buf_1 _415_ (
    .A(_159_),
    .X(_160_)
  );
  sky130_fd_sc_hd__buf_1 _416_ (
    .A(_160_),
    .X(_161_)
  );
  sky130_fd_sc_hd__o41a_2 _417_ (
    .A1(data_valid),
    .A2(read_cmd),
    .A3(\u_command_generator.state[6] ),
    .A4(_158_),
    .B1(_161_),
    .X(_013_)
  );
  sky130_fd_sc_hd__or4_2 _418_ (
    .A(\u_sdram_init.delay_counter[15] ),
    .B(\u_sdram_init.delay_counter[10] ),
    .C(\u_sdram_init.delay_counter[9] ),
    .D(\u_sdram_init.delay_counter[8] ),
    .X(_162_)
  );
  sky130_fd_sc_hd__or4_2 _419_ (
    .A(\u_sdram_init.delay_counter[14] ),
    .B(\u_sdram_init.delay_counter[13] ),
    .C(\u_sdram_init.delay_counter[12] ),
    .D(\u_sdram_init.delay_counter[11] ),
    .X(_163_)
  );
  sky130_fd_sc_hd__or4_2 _420_ (
    .A(\u_sdram_init.delay_counter[7] ),
    .B(\u_sdram_init.delay_counter[6] ),
    .C(\u_sdram_init.delay_counter[5] ),
    .D(\u_sdram_init.delay_counter[4] ),
    .X(_164_)
  );
  sky130_fd_sc_hd__or4b_2 _421_ (
    .A(\u_sdram_init.delay_counter[3] ),
    .B(\u_sdram_init.delay_counter[2] ),
    .C(\u_sdram_init.delay_counter[1] ),
    .D_N(\u_sdram_init.delay_counter[0] ),
    .X(_165_)
  );
  sky130_fd_sc_hd__or4_2 _422_ (
    .A(_162_),
    .B(_163_),
    .C(_164_),
    .D(_165_),
    .X(_166_)
  );
  sky130_fd_sc_hd__or3b_2 _423_ (
    .A(\u_sdram_init.state[2] ),
    .B(\u_sdram_init.state[1] ),
    .C_N(\u_sdram_init.state[0] ),
    .X(_167_)
  );
  sky130_fd_sc_hd__nor2_2 _424_ (
    .A(_166_),
    .B(_167_),
    .Y(precharge_all_cmd)
  );
  sky130_fd_sc_hd__or3_2 _425_ (
    .A(data_valid),
    .B(read_cmd),
    .C(precharge_cmd),
    .X(_168_)
  );
  sky130_fd_sc_hd__or2_2 _426_ (
    .A(activate_cmd),
    .B(_168_),
    .X(_169_)
  );
  sky130_fd_sc_hd__buf_1 _427_ (
    .A(_169_),
    .X(_170_)
  );
  sky130_fd_sc_hd__and2_2 _428_ (
    .A(\u_bank_manager.query_bank[0] ),
    .B(_170_),
    .X(_171_)
  );
  sky130_fd_sc_hd__buf_1 _429_ (
    .A(_171_),
    .X(bank_cmd[0])
  );
  sky130_fd_sc_hd__and2_2 _430_ (
    .A(\u_bank_manager.query_bank[1] ),
    .B(_170_),
    .X(_172_)
  );
  sky130_fd_sc_hd__buf_1 _431_ (
    .A(_172_),
    .X(bank_cmd[1])
  );
  sky130_fd_sc_hd__inv_2 _432_ (
    .A(\u_command_generator.precharge_for_miss ),
    .Y(_173_)
  );
  sky130_fd_sc_hd__and3b_2 _433_ (
    .A_N(\u_sdram_init.state[1] ),
    .B(\u_sdram_init.state[0] ),
    .C(\u_sdram_init.state[2] ),
    .X(_174_)
  );
  sky130_fd_sc_hd__buf_1 _434_ (
    .A(_174_),
    .X(init_done)
  );
  sky130_fd_sc_hd__a21boi_2 _435_ (
    .A1(\u_command_generator.req_pending ),
    .A2(init_done),
    .B1_N(\u_command_generator.state[0] ),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a311o_2 _436_ (
    .A1(_173_),
    .A2(\u_command_generator.state[1] ),
    .A3(_157_),
    .B1(_175_),
    .C1(_151_),
    .X(_004_)
  );
  sky130_fd_sc_hd__a32o_2 _437_ (
    .A1(_128_),
    .A2(_137_),
    .A3(_146_),
    .B1(_157_),
    .B2(\u_command_generator.state[7] ),
    .X(_176_)
  );
  sky130_fd_sc_hd__and3_2 _438_ (
    .A(_160_),
    .B(_158_),
    .C(_176_),
    .X(_177_)
  );
  sky130_fd_sc_hd__buf_1 _439_ (
    .A(_177_),
    .X(_006_)
  );
  sky130_fd_sc_hd__a21oi_2 _440_ (
    .A1(\u_command_generator.state[1] ),
    .A2(_153_),
    .B1(precharge_cmd),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nor2_2 _441_ (
    .A(_151_),
    .B(_178_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and2b_2 _442_ (
    .A_N(_147_),
    .B(\u_command_generator.state[5] ),
    .X(_179_)
  );
  sky130_fd_sc_hd__and3_2 _443_ (
    .A(\u_command_generator.precharge_for_miss ),
    .B(\u_command_generator.state[1] ),
    .C(_157_),
    .X(_180_)
  );
  sky130_fd_sc_hd__o21a_2 _444_ (
    .A1(_179_),
    .A2(_180_),
    .B1(_161_),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand3_2 _445_ (
    .A(\u_command_generator.req_pending ),
    .B(\u_command_generator.state[0] ),
    .C(init_done),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nor2_2 _446_ (
    .A(_151_),
    .B(_181_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a21o_2 _447_ (
    .A1(\u_command_generator.state[7] ),
    .A2(_153_),
    .B1(data_valid),
    .X(_182_)
  );
  sky130_fd_sc_hd__nor3b_2 _448_ (
    .A(_182_),
    .B(_154_),
    .C_N(_156_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__a31oi_2 _449_ (
    .A1(_149_),
    .A2(_181_),
    .A3(_183_),
    .B1(_151_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__and3_2 _450_ (
    .A(_160_),
    .B(\u_command_generator.state[6] ),
    .C(_157_),
    .X(_184_)
  );
  sky130_fd_sc_hd__buf_1 _451_ (
    .A(_184_),
    .X(_002_)
  );
  sky130_fd_sc_hd__a21o_2 _452_ (
    .A1(\u_command_generator.precharge_for_miss ),
    .A2(\u_command_generator.state[1] ),
    .B1(\u_command_generator.state[6] ),
    .X(_185_)
  );
  sky130_fd_sc_hd__a211o_2 _453_ (
    .A1(_157_),
    .A2(_185_),
    .B1(_182_),
    .C1(_179_),
    .X(_186_)
  );
  sky130_fd_sc_hd__nor2_2 _454_ (
    .A(_154_),
    .B(_186_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a21oi_2 _455_ (
    .A1(_149_),
    .A2(_187_),
    .B1(_151_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__and3b_2 _456_ (
    .A_N(\u_command_generator.req_pending ),
    .B(\u_command_generator.state[0] ),
    .C(init_done),
    .X(_188_)
  );
  sky130_fd_sc_hd__buf_1 _457_ (
    .A(_188_),
    .X(ready)
  );
  sky130_fd_sc_hd__and2_2 _458_ (
    .A(\u_command_generator.request_row_reg[0] ),
    .B(_170_),
    .X(_189_)
  );
  sky130_fd_sc_hd__buf_1 _459_ (
    .A(_189_),
    .X(row_cmd[0])
  );
  sky130_fd_sc_hd__and2_2 _460_ (
    .A(\u_command_generator.request_row_reg[1] ),
    .B(_170_),
    .X(_190_)
  );
  sky130_fd_sc_hd__buf_1 _461_ (
    .A(_190_),
    .X(row_cmd[1])
  );
  sky130_fd_sc_hd__and2_2 _462_ (
    .A(\u_command_generator.request_row_reg[2] ),
    .B(_170_),
    .X(_191_)
  );
  sky130_fd_sc_hd__buf_1 _463_ (
    .A(_191_),
    .X(row_cmd[2])
  );
  sky130_fd_sc_hd__and2_2 _464_ (
    .A(\u_command_generator.request_row_reg[3] ),
    .B(_170_),
    .X(_192_)
  );
  sky130_fd_sc_hd__buf_1 _465_ (
    .A(_192_),
    .X(row_cmd[3])
  );
  sky130_fd_sc_hd__and2_2 _466_ (
    .A(\u_command_generator.request_row_reg[4] ),
    .B(_170_),
    .X(_193_)
  );
  sky130_fd_sc_hd__buf_1 _467_ (
    .A(_193_),
    .X(row_cmd[4])
  );
  sky130_fd_sc_hd__and2_2 _468_ (
    .A(\u_command_generator.request_row_reg[5] ),
    .B(_170_),
    .X(_194_)
  );
  sky130_fd_sc_hd__buf_1 _469_ (
    .A(_194_),
    .X(row_cmd[5])
  );
  sky130_fd_sc_hd__and2_2 _470_ (
    .A(\u_command_generator.request_row_reg[6] ),
    .B(_170_),
    .X(_195_)
  );
  sky130_fd_sc_hd__buf_1 _471_ (
    .A(_195_),
    .X(row_cmd[6])
  );
  sky130_fd_sc_hd__and2_2 _472_ (
    .A(\u_command_generator.request_row_reg[7] ),
    .B(_170_),
    .X(_196_)
  );
  sky130_fd_sc_hd__buf_1 _473_ (
    .A(_196_),
    .X(row_cmd[7])
  );
  sky130_fd_sc_hd__and2_2 _474_ (
    .A(\u_command_generator.request_row_reg[8] ),
    .B(_169_),
    .X(_197_)
  );
  sky130_fd_sc_hd__buf_1 _475_ (
    .A(_197_),
    .X(row_cmd[8])
  );
  sky130_fd_sc_hd__and2_2 _476_ (
    .A(\u_command_generator.request_row_reg[9] ),
    .B(_169_),
    .X(_198_)
  );
  sky130_fd_sc_hd__buf_1 _477_ (
    .A(_198_),
    .X(row_cmd[9])
  );
  sky130_fd_sc_hd__and2_2 _478_ (
    .A(\u_command_generator.request_row_reg[10] ),
    .B(_169_),
    .X(_199_)
  );
  sky130_fd_sc_hd__buf_1 _479_ (
    .A(_199_),
    .X(row_cmd[10])
  );
  sky130_fd_sc_hd__and2_2 _480_ (
    .A(\u_command_generator.request_row_reg[11] ),
    .B(_169_),
    .X(_200_)
  );
  sky130_fd_sc_hd__buf_1 _481_ (
    .A(_200_),
    .X(row_cmd[11])
  );
  sky130_fd_sc_hd__and2_2 _482_ (
    .A(\u_command_generator.request_column_reg[0] ),
    .B(_168_),
    .X(_201_)
  );
  sky130_fd_sc_hd__buf_1 _483_ (
    .A(_201_),
    .X(column_cmd[0])
  );
  sky130_fd_sc_hd__and2_2 _484_ (
    .A(\u_command_generator.request_column_reg[1] ),
    .B(_168_),
    .X(_202_)
  );
  sky130_fd_sc_hd__buf_1 _485_ (
    .A(_202_),
    .X(column_cmd[1])
  );
  sky130_fd_sc_hd__and2_2 _486_ (
    .A(\u_command_generator.request_column_reg[2] ),
    .B(_168_),
    .X(_203_)
  );
  sky130_fd_sc_hd__buf_1 _487_ (
    .A(_203_),
    .X(column_cmd[2])
  );
  sky130_fd_sc_hd__and2_2 _488_ (
    .A(\u_command_generator.request_column_reg[3] ),
    .B(_168_),
    .X(_204_)
  );
  sky130_fd_sc_hd__buf_1 _489_ (
    .A(_204_),
    .X(column_cmd[3])
  );
  sky130_fd_sc_hd__and2_2 _490_ (
    .A(\u_command_generator.request_column_reg[4] ),
    .B(_168_),
    .X(_205_)
  );
  sky130_fd_sc_hd__buf_1 _491_ (
    .A(_205_),
    .X(column_cmd[4])
  );
  sky130_fd_sc_hd__and2_2 _492_ (
    .A(\u_command_generator.request_column_reg[5] ),
    .B(_168_),
    .X(_206_)
  );
  sky130_fd_sc_hd__buf_1 _493_ (
    .A(_206_),
    .X(column_cmd[5])
  );
  sky130_fd_sc_hd__and2_2 _494_ (
    .A(\u_command_generator.request_column_reg[6] ),
    .B(_168_),
    .X(_207_)
  );
  sky130_fd_sc_hd__buf_1 _495_ (
    .A(_207_),
    .X(column_cmd[6])
  );
  sky130_fd_sc_hd__and2_2 _496_ (
    .A(\u_command_generator.request_column_reg[7] ),
    .B(_168_),
    .X(_208_)
  );
  sky130_fd_sc_hd__buf_1 _497_ (
    .A(_208_),
    .X(column_cmd[7])
  );
  sky130_fd_sc_hd__nor2_2 _498_ (
    .A(_162_),
    .B(_163_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nor4_2 _499_ (
    .A(\u_sdram_init.delay_counter[7] ),
    .B(\u_sdram_init.delay_counter[6] ),
    .C(\u_sdram_init.delay_counter[5] ),
    .D(\u_sdram_init.delay_counter[4] ),
    .Y(_210_)
  );
  sky130_fd_sc_hd__inv_2 _500_ (
    .A(\u_sdram_init.delay_counter[0] ),
    .Y(_211_)
  );
  sky130_fd_sc_hd__buf_1 _501_ (
    .A(\u_sdram_init.state[1] ),
    .X(_212_)
  );
  sky130_fd_sc_hd__and4bb_2 _502_ (
    .A_N(\u_sdram_init.delay_counter[3] ),
    .B_N(\u_sdram_init.state[2] ),
    .C(_212_),
    .D(\u_sdram_init.delay_counter[2] ),
    .X(_213_)
  );
  sky130_fd_sc_hd__and3_2 _503_ (
    .A(\u_sdram_init.delay_counter[1] ),
    .B(_211_),
    .C(_213_),
    .X(_214_)
  );
  sky130_fd_sc_hd__and3_2 _504_ (
    .A(_209_),
    .B(_210_),
    .C(_214_),
    .X(_215_)
  );
  sky130_fd_sc_hd__buf_1 _505_ (
    .A(_215_),
    .X(refresh_cmd)
  );
  sky130_fd_sc_hd__buf_1 _506_ (
    .A(\u_sdram_init.state[2] ),
    .X(_216_)
  );
  sky130_fd_sc_hd__nor4b_2 _507_ (
    .A(_212_),
    .B(\u_sdram_init.state[0] ),
    .C(_166_),
    .D_N(_216_),
    .Y(load_mode_cmd)
  );
  sky130_fd_sc_hd__nor3_2 _508_ (
    .A(\u_command_generator.delay_counter[1] ),
    .B(\u_command_generator.delay_counter[0] ),
    .C(\u_command_generator.delay_counter[2] ),
    .Y(_217_)
  );
  sky130_fd_sc_hd__o21a_2 _509_ (
    .A1(\u_command_generator.delay_counter[1] ),
    .A2(\u_command_generator.delay_counter[0] ),
    .B1(\u_command_generator.delay_counter[2] ),
    .X(_218_)
  );
  sky130_fd_sc_hd__nor4_2 _510_ (
    .A(_150_),
    .B(_154_),
    .C(read_cmd),
    .D(precharge_cmd),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o211a_2 _511_ (
    .A1(_217_),
    .A2(_218_),
    .B1(_219_),
    .C1(_153_),
    .X(_014_)
  );
  sky130_fd_sc_hd__and3b_2 _512_ (
    .A_N(_217_),
    .B(_219_),
    .C(\u_command_generator.delay_counter[3] ),
    .X(_220_)
  );
  sky130_fd_sc_hd__buf_1 _513_ (
    .A(_220_),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor2_2 _514_ (
    .A(\u_command_generator.delay_counter[0] ),
    .B(_157_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__o21ba_2 _515_ (
    .A1(precharge_cmd),
    .A2(_221_),
    .B1_N(read_cmd),
    .X(_222_)
  );
  sky130_fd_sc_hd__o21a_2 _516_ (
    .A1(_154_),
    .A2(_222_),
    .B1(_161_),
    .X(_016_)
  );
  sky130_fd_sc_hd__or2b_2 _517_ (
    .A(\u_command_generator.state[5] ),
    .B_N(\u_command_generator.precharge_for_miss ),
    .X(_223_)
  );
  sky130_fd_sc_hd__inv_2 _518_ (
    .A(\u_command_generator.state[1] ),
    .Y(_224_)
  );
  sky130_fd_sc_hd__or4_2 _519_ (
    .A(read_cmd),
    .B(\u_command_generator.state[6] ),
    .C(precharge_cmd),
    .D(\u_command_generator.state[0] ),
    .X(_225_)
  );
  sky130_fd_sc_hd__nor4_2 _520_ (
    .A(_224_),
    .B(_153_),
    .C(_158_),
    .D(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__a31o_2 _521_ (
    .A1(_183_),
    .A2(_186_),
    .A3(_226_),
    .B1(_150_),
    .X(_227_)
  );
  sky130_fd_sc_hd__a21oi_2 _522_ (
    .A1(_149_),
    .A2(_223_),
    .B1(_227_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a21oi_2 _523_ (
    .A1(\u_command_generator.req_pending ),
    .A2(_181_),
    .B1(req_ack),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor2_2 _524_ (
    .A(_151_),
    .B(_228_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__mux2_2 _525_ (
    .A0(\u_command_generator.request_column_reg[0] ),
    .A1(address[2]),
    .S(req_ack),
    .X(_229_)
  );
  sky130_fd_sc_hd__and2_2 _526_ (
    .A(_161_),
    .B(_229_),
    .X(_230_)
  );
  sky130_fd_sc_hd__buf_1 _527_ (
    .A(_230_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_2 _528_ (
    .A0(\u_command_generator.request_column_reg[1] ),
    .A1(address[3]),
    .S(req_ack),
    .X(_231_)
  );
  sky130_fd_sc_hd__and2_2 _529_ (
    .A(_161_),
    .B(_231_),
    .X(_232_)
  );
  sky130_fd_sc_hd__buf_1 _530_ (
    .A(_232_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_2 _531_ (
    .A0(\u_command_generator.request_column_reg[2] ),
    .A1(address[4]),
    .S(req_ack),
    .X(_233_)
  );
  sky130_fd_sc_hd__and2_2 _532_ (
    .A(_161_),
    .B(_233_),
    .X(_234_)
  );
  sky130_fd_sc_hd__buf_1 _533_ (
    .A(_234_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_2 _534_ (
    .A0(\u_command_generator.request_column_reg[3] ),
    .A1(address[5]),
    .S(req_ack),
    .X(_235_)
  );
  sky130_fd_sc_hd__and2_2 _535_ (
    .A(_161_),
    .B(_235_),
    .X(_236_)
  );
  sky130_fd_sc_hd__buf_1 _536_ (
    .A(_236_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_2 _537_ (
    .A0(\u_command_generator.request_column_reg[4] ),
    .A1(address[6]),
    .S(req_ack),
    .X(_237_)
  );
  sky130_fd_sc_hd__and2_2 _538_ (
    .A(_161_),
    .B(_237_),
    .X(_238_)
  );
  sky130_fd_sc_hd__buf_1 _539_ (
    .A(_238_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_2 _540_ (
    .A0(\u_command_generator.request_column_reg[5] ),
    .A1(address[7]),
    .S(req_ack),
    .X(_239_)
  );
  sky130_fd_sc_hd__and2_2 _541_ (
    .A(_161_),
    .B(_239_),
    .X(_240_)
  );
  sky130_fd_sc_hd__buf_1 _542_ (
    .A(_240_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_2 _543_ (
    .A0(\u_command_generator.request_column_reg[6] ),
    .A1(address[8]),
    .S(req_ack),
    .X(_241_)
  );
  sky130_fd_sc_hd__and2_2 _544_ (
    .A(_161_),
    .B(_241_),
    .X(_242_)
  );
  sky130_fd_sc_hd__buf_1 _545_ (
    .A(_242_),
    .X(_025_)
  );
  sky130_fd_sc_hd__buf_1 _546_ (
    .A(_159_),
    .X(_243_)
  );
  sky130_fd_sc_hd__mux2_2 _547_ (
    .A0(\u_command_generator.request_column_reg[7] ),
    .A1(address[9]),
    .S(req_ack),
    .X(_244_)
  );
  sky130_fd_sc_hd__and2_2 _548_ (
    .A(_243_),
    .B(_244_),
    .X(_245_)
  );
  sky130_fd_sc_hd__buf_1 _549_ (
    .A(_245_),
    .X(_026_)
  );
  sky130_fd_sc_hd__buf_1 _550_ (
    .A(_116_),
    .X(_246_)
  );
  sky130_fd_sc_hd__mux2_2 _551_ (
    .A0(\u_command_generator.request_row_reg[0] ),
    .A1(address[10]),
    .S(_246_),
    .X(_247_)
  );
  sky130_fd_sc_hd__and2_2 _552_ (
    .A(_243_),
    .B(_247_),
    .X(_248_)
  );
  sky130_fd_sc_hd__buf_1 _553_ (
    .A(_248_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_2 _554_ (
    .A0(\u_command_generator.request_row_reg[1] ),
    .A1(address[11]),
    .S(_246_),
    .X(_249_)
  );
  sky130_fd_sc_hd__and2_2 _555_ (
    .A(_243_),
    .B(_249_),
    .X(_250_)
  );
  sky130_fd_sc_hd__buf_1 _556_ (
    .A(_250_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_2 _557_ (
    .A0(\u_command_generator.request_row_reg[2] ),
    .A1(address[12]),
    .S(_246_),
    .X(_251_)
  );
  sky130_fd_sc_hd__and2_2 _558_ (
    .A(_243_),
    .B(_251_),
    .X(_252_)
  );
  sky130_fd_sc_hd__buf_1 _559_ (
    .A(_252_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_2 _560_ (
    .A0(\u_command_generator.request_row_reg[3] ),
    .A1(address[13]),
    .S(_246_),
    .X(_253_)
  );
  sky130_fd_sc_hd__and2_2 _561_ (
    .A(_243_),
    .B(_253_),
    .X(_254_)
  );
  sky130_fd_sc_hd__buf_1 _562_ (
    .A(_254_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_2 _563_ (
    .A0(\u_command_generator.request_row_reg[4] ),
    .A1(address[14]),
    .S(_246_),
    .X(_255_)
  );
  sky130_fd_sc_hd__and2_2 _564_ (
    .A(_243_),
    .B(_255_),
    .X(_256_)
  );
  sky130_fd_sc_hd__buf_1 _565_ (
    .A(_256_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_2 _566_ (
    .A0(\u_command_generator.request_row_reg[5] ),
    .A1(address[15]),
    .S(_246_),
    .X(_257_)
  );
  sky130_fd_sc_hd__and2_2 _567_ (
    .A(_243_),
    .B(_257_),
    .X(_258_)
  );
  sky130_fd_sc_hd__buf_1 _568_ (
    .A(_258_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_2 _569_ (
    .A0(\u_command_generator.request_row_reg[6] ),
    .A1(address[16]),
    .S(_246_),
    .X(_259_)
  );
  sky130_fd_sc_hd__and2_2 _570_ (
    .A(_243_),
    .B(_259_),
    .X(_260_)
  );
  sky130_fd_sc_hd__buf_1 _571_ (
    .A(_260_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_2 _572_ (
    .A0(\u_command_generator.request_row_reg[7] ),
    .A1(address[17]),
    .S(_246_),
    .X(_261_)
  );
  sky130_fd_sc_hd__and2_2 _573_ (
    .A(_243_),
    .B(_261_),
    .X(_262_)
  );
  sky130_fd_sc_hd__buf_1 _574_ (
    .A(_262_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_2 _575_ (
    .A0(\u_command_generator.request_row_reg[8] ),
    .A1(address[18]),
    .S(_246_),
    .X(_263_)
  );
  sky130_fd_sc_hd__and2_2 _576_ (
    .A(_243_),
    .B(_263_),
    .X(_264_)
  );
  sky130_fd_sc_hd__buf_1 _577_ (
    .A(_264_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_2 _578_ (
    .A0(\u_command_generator.request_row_reg[9] ),
    .A1(address[19]),
    .S(_246_),
    .X(_265_)
  );
  sky130_fd_sc_hd__and2_2 _579_ (
    .A(_160_),
    .B(_265_),
    .X(_266_)
  );
  sky130_fd_sc_hd__buf_1 _580_ (
    .A(_266_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_2 _581_ (
    .A0(\u_command_generator.request_row_reg[10] ),
    .A1(address[20]),
    .S(_116_),
    .X(_267_)
  );
  sky130_fd_sc_hd__and2_2 _582_ (
    .A(_160_),
    .B(_267_),
    .X(_268_)
  );
  sky130_fd_sc_hd__buf_1 _583_ (
    .A(_268_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_2 _584_ (
    .A0(\u_command_generator.request_row_reg[11] ),
    .A1(address[21]),
    .S(_116_),
    .X(_269_)
  );
  sky130_fd_sc_hd__and2_2 _585_ (
    .A(_160_),
    .B(_269_),
    .X(_270_)
  );
  sky130_fd_sc_hd__buf_1 _586_ (
    .A(_270_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_2 _587_ (
    .A0(\u_bank_manager.query_bank[0] ),
    .A1(address[22]),
    .S(_116_),
    .X(_271_)
  );
  sky130_fd_sc_hd__and2_2 _588_ (
    .A(_160_),
    .B(_271_),
    .X(_272_)
  );
  sky130_fd_sc_hd__buf_1 _589_ (
    .A(_272_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_2 _590_ (
    .A0(\u_bank_manager.query_bank[1] ),
    .A1(address[23]),
    .S(_116_),
    .X(_273_)
  );
  sky130_fd_sc_hd__and2_2 _591_ (
    .A(_160_),
    .B(_273_),
    .X(_274_)
  );
  sky130_fd_sc_hd__buf_1 _592_ (
    .A(_274_),
    .X(_040_)
  );
  sky130_fd_sc_hd__inv_2 _593_ (
    .A(precharge_cmd),
    .Y(_275_)
  );
  sky130_fd_sc_hd__mux2_2 _594_ (
    .A0(_221_),
    .A1(\u_command_generator.delay_counter[0] ),
    .S(\u_command_generator.delay_counter[1] ),
    .X(_276_)
  );
  sky130_fd_sc_hd__a21oi_2 _595_ (
    .A1(_275_),
    .A2(_276_),
    .B1(read_cmd),
    .Y(_277_)
  );
  sky130_fd_sc_hd__nor3_2 _596_ (
    .A(_150_),
    .B(_154_),
    .C(_277_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21ai_2 _597_ (
    .A1(\u_bank_manager.query_bank[1] ),
    .A2(\u_bank_manager.query_bank[0] ),
    .B1(_169_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__buf_1 _598_ (
    .A(_278_),
    .X(_279_)
  );
  sky130_fd_sc_hd__o211a_2 _599_ (
    .A1(_166_),
    .A2(_167_),
    .B1(activate_cmd),
    .C1(_275_),
    .X(_280_)
  );
  sky130_fd_sc_hd__and2_2 _600_ (
    .A(_159_),
    .B(_280_),
    .X(_281_)
  );
  sky130_fd_sc_hd__buf_1 _601_ (
    .A(_281_),
    .X(_282_)
  );
  sky130_fd_sc_hd__buf_1 _602_ (
    .A(_282_),
    .X(_283_)
  );
  sky130_fd_sc_hd__a21oi_2 _603_ (
    .A1(_278_),
    .A2(_280_),
    .B1(_150_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__buf_1 _604_ (
    .A(_284_),
    .X(_285_)
  );
  sky130_fd_sc_hd__a32o_2 _605_ (
    .A1(row_cmd[0]),
    .A2(_279_),
    .A3(_283_),
    .B1(_285_),
    .B2(\u_bank_manager.active_row_reg[0][0] ),
    .X(_042_)
  );
  sky130_fd_sc_hd__a32o_2 _606_ (
    .A1(row_cmd[1]),
    .A2(_279_),
    .A3(_283_),
    .B1(_285_),
    .B2(\u_bank_manager.active_row_reg[0][1] ),
    .X(_043_)
  );
  sky130_fd_sc_hd__a32o_2 _607_ (
    .A1(row_cmd[2]),
    .A2(_279_),
    .A3(_283_),
    .B1(_285_),
    .B2(\u_bank_manager.active_row_reg[0][2] ),
    .X(_044_)
  );
  sky130_fd_sc_hd__a32o_2 _608_ (
    .A1(row_cmd[3]),
    .A2(_279_),
    .A3(_283_),
    .B1(_285_),
    .B2(\u_bank_manager.active_row_reg[0][3] ),
    .X(_045_)
  );
  sky130_fd_sc_hd__a32o_2 _609_ (
    .A1(row_cmd[4]),
    .A2(_279_),
    .A3(_283_),
    .B1(_285_),
    .B2(\u_bank_manager.active_row_reg[0][4] ),
    .X(_046_)
  );
  sky130_fd_sc_hd__a32o_2 _610_ (
    .A1(row_cmd[5]),
    .A2(_279_),
    .A3(_283_),
    .B1(_285_),
    .B2(\u_bank_manager.active_row_reg[0][5] ),
    .X(_047_)
  );
  sky130_fd_sc_hd__a32o_2 _611_ (
    .A1(row_cmd[6]),
    .A2(_279_),
    .A3(_283_),
    .B1(_285_),
    .B2(\u_bank_manager.active_row_reg[0][6] ),
    .X(_048_)
  );
  sky130_fd_sc_hd__a32o_2 _612_ (
    .A1(row_cmd[7]),
    .A2(_279_),
    .A3(_283_),
    .B1(_285_),
    .B2(\u_bank_manager.active_row_reg[0][7] ),
    .X(_049_)
  );
  sky130_fd_sc_hd__a32o_2 _613_ (
    .A1(row_cmd[8]),
    .A2(_279_),
    .A3(_283_),
    .B1(_285_),
    .B2(\u_bank_manager.active_row_reg[0][8] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__a32o_2 _614_ (
    .A1(row_cmd[9]),
    .A2(_279_),
    .A3(_283_),
    .B1(_285_),
    .B2(\u_bank_manager.active_row_reg[0][9] ),
    .X(_051_)
  );
  sky130_fd_sc_hd__buf_1 _615_ (
    .A(_281_),
    .X(_286_)
  );
  sky130_fd_sc_hd__a32o_2 _616_ (
    .A1(row_cmd[10]),
    .A2(_278_),
    .A3(_286_),
    .B1(_284_),
    .B2(\u_bank_manager.active_row_reg[0][10] ),
    .X(_052_)
  );
  sky130_fd_sc_hd__a32o_2 _617_ (
    .A1(row_cmd[11]),
    .A2(_278_),
    .A3(_286_),
    .B1(_284_),
    .B2(\u_bank_manager.active_row_reg[0][11] ),
    .X(_053_)
  );
  sky130_fd_sc_hd__nor4_2 _618_ (
    .A(\u_sdram_init.delay_counter[3] ),
    .B(\u_sdram_init.delay_counter[2] ),
    .C(\u_sdram_init.delay_counter[1] ),
    .D(\u_sdram_init.delay_counter[0] ),
    .Y(_287_)
  );
  sky130_fd_sc_hd__and4bb_2 _619_ (
    .A_N(_162_),
    .B_N(_163_),
    .C(_210_),
    .D(_287_),
    .X(_288_)
  );
  sky130_fd_sc_hd__or4_2 _620_ (
    .A(\u_sdram_init.delay_counter[3] ),
    .B(\u_sdram_init.delay_counter[2] ),
    .C(\u_sdram_init.delay_counter[1] ),
    .D(\u_sdram_init.delay_counter[0] ),
    .X(_289_)
  );
  sky130_fd_sc_hd__buf_1 _621_ (
    .A(_289_),
    .X(_290_)
  );
  sky130_fd_sc_hd__or4_2 _622_ (
    .A(_162_),
    .B(_163_),
    .C(_164_),
    .D(_290_),
    .X(_291_)
  );
  sky130_fd_sc_hd__or3b_2 _623_ (
    .A(_291_),
    .B(_216_),
    .C_N(\u_sdram_init.state[0] ),
    .X(_292_)
  );
  sky130_fd_sc_hd__a21oi_2 _624_ (
    .A1(_216_),
    .A2(_212_),
    .B1(_150_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__o211a_2 _625_ (
    .A1(\u_sdram_init.state[0] ),
    .A2(_288_),
    .B1(_292_),
    .C1(_293_),
    .X(_054_)
  );
  sky130_fd_sc_hd__a21oi_2 _626_ (
    .A1(\u_sdram_init.state[0] ),
    .A2(_288_),
    .B1(_212_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__a31o_2 _627_ (
    .A1(_212_),
    .A2(\u_sdram_init.state[0] ),
    .A3(_288_),
    .B1(_216_),
    .X(_295_)
  );
  sky130_fd_sc_hd__nor3_2 _628_ (
    .A(_150_),
    .B(_294_),
    .C(_295_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__and2_2 _629_ (
    .A(_293_),
    .B(_295_),
    .X(_296_)
  );
  sky130_fd_sc_hd__buf_1 _630_ (
    .A(_296_),
    .X(_056_)
  );
  sky130_fd_sc_hd__and3b_2 _631_ (
    .A_N(\u_bank_manager.query_bank[0] ),
    .B(_169_),
    .C(\u_bank_manager.query_bank[1] ),
    .X(_297_)
  );
  sky130_fd_sc_hd__buf_1 _632_ (
    .A(_297_),
    .X(_298_)
  );
  sky130_fd_sc_hd__buf_1 _633_ (
    .A(_298_),
    .X(_299_)
  );
  sky130_fd_sc_hd__a21oi_2 _634_ (
    .A1(_280_),
    .A2(_298_),
    .B1(reset),
    .Y(_300_)
  );
  sky130_fd_sc_hd__buf_1 _635_ (
    .A(_300_),
    .X(_301_)
  );
  sky130_fd_sc_hd__a32o_2 _636_ (
    .A1(row_cmd[0]),
    .A2(_286_),
    .A3(_299_),
    .B1(_301_),
    .B2(\u_bank_manager.active_row_reg[2][0] ),
    .X(_057_)
  );
  sky130_fd_sc_hd__a32o_2 _637_ (
    .A1(row_cmd[1]),
    .A2(_286_),
    .A3(_299_),
    .B1(_301_),
    .B2(\u_bank_manager.active_row_reg[2][1] ),
    .X(_058_)
  );
  sky130_fd_sc_hd__a32o_2 _638_ (
    .A1(row_cmd[2]),
    .A2(_286_),
    .A3(_299_),
    .B1(_301_),
    .B2(\u_bank_manager.active_row_reg[2][2] ),
    .X(_059_)
  );
  sky130_fd_sc_hd__a32o_2 _639_ (
    .A1(row_cmd[3]),
    .A2(_286_),
    .A3(_299_),
    .B1(_301_),
    .B2(\u_bank_manager.active_row_reg[2][3] ),
    .X(_060_)
  );
  sky130_fd_sc_hd__a32o_2 _640_ (
    .A1(row_cmd[4]),
    .A2(_286_),
    .A3(_299_),
    .B1(_301_),
    .B2(\u_bank_manager.active_row_reg[2][4] ),
    .X(_061_)
  );
  sky130_fd_sc_hd__a32o_2 _641_ (
    .A1(row_cmd[5]),
    .A2(_286_),
    .A3(_299_),
    .B1(_301_),
    .B2(\u_bank_manager.active_row_reg[2][5] ),
    .X(_062_)
  );
  sky130_fd_sc_hd__a32o_2 _642_ (
    .A1(row_cmd[6]),
    .A2(_286_),
    .A3(_299_),
    .B1(_301_),
    .B2(\u_bank_manager.active_row_reg[2][6] ),
    .X(_063_)
  );
  sky130_fd_sc_hd__a32o_2 _643_ (
    .A1(row_cmd[7]),
    .A2(_286_),
    .A3(_299_),
    .B1(_301_),
    .B2(\u_bank_manager.active_row_reg[2][7] ),
    .X(_064_)
  );
  sky130_fd_sc_hd__buf_1 _644_ (
    .A(_282_),
    .X(_302_)
  );
  sky130_fd_sc_hd__a32o_2 _645_ (
    .A1(row_cmd[8]),
    .A2(_302_),
    .A3(_299_),
    .B1(_301_),
    .B2(\u_bank_manager.active_row_reg[2][8] ),
    .X(_065_)
  );
  sky130_fd_sc_hd__a32o_2 _646_ (
    .A1(row_cmd[9]),
    .A2(_302_),
    .A3(_299_),
    .B1(_301_),
    .B2(\u_bank_manager.active_row_reg[2][9] ),
    .X(_066_)
  );
  sky130_fd_sc_hd__a32o_2 _647_ (
    .A1(row_cmd[10]),
    .A2(_302_),
    .A3(_298_),
    .B1(_300_),
    .B2(\u_bank_manager.active_row_reg[2][10] ),
    .X(_067_)
  );
  sky130_fd_sc_hd__a32o_2 _648_ (
    .A1(row_cmd[11]),
    .A2(_302_),
    .A3(_298_),
    .B1(_300_),
    .B2(\u_bank_manager.active_row_reg[2][11] ),
    .X(_068_)
  );
  sky130_fd_sc_hd__and3b_2 _649_ (
    .A_N(\u_bank_manager.query_bank[1] ),
    .B(\u_bank_manager.query_bank[0] ),
    .C(_169_),
    .X(_303_)
  );
  sky130_fd_sc_hd__buf_1 _650_ (
    .A(_303_),
    .X(_304_)
  );
  sky130_fd_sc_hd__buf_1 _651_ (
    .A(_304_),
    .X(_305_)
  );
  sky130_fd_sc_hd__a21oi_2 _652_ (
    .A1(_280_),
    .A2(_304_),
    .B1(reset),
    .Y(_306_)
  );
  sky130_fd_sc_hd__buf_1 _653_ (
    .A(_306_),
    .X(_307_)
  );
  sky130_fd_sc_hd__a32o_2 _654_ (
    .A1(row_cmd[0]),
    .A2(_302_),
    .A3(_305_),
    .B1(_307_),
    .B2(\u_bank_manager.active_row_reg[1][0] ),
    .X(_069_)
  );
  sky130_fd_sc_hd__a32o_2 _655_ (
    .A1(row_cmd[1]),
    .A2(_302_),
    .A3(_305_),
    .B1(_307_),
    .B2(\u_bank_manager.active_row_reg[1][1] ),
    .X(_070_)
  );
  sky130_fd_sc_hd__a32o_2 _656_ (
    .A1(row_cmd[2]),
    .A2(_302_),
    .A3(_305_),
    .B1(_307_),
    .B2(\u_bank_manager.active_row_reg[1][2] ),
    .X(_071_)
  );
  sky130_fd_sc_hd__a32o_2 _657_ (
    .A1(row_cmd[3]),
    .A2(_302_),
    .A3(_305_),
    .B1(_307_),
    .B2(\u_bank_manager.active_row_reg[1][3] ),
    .X(_072_)
  );
  sky130_fd_sc_hd__a32o_2 _658_ (
    .A1(row_cmd[4]),
    .A2(_302_),
    .A3(_305_),
    .B1(_307_),
    .B2(\u_bank_manager.active_row_reg[1][4] ),
    .X(_073_)
  );
  sky130_fd_sc_hd__a32o_2 _659_ (
    .A1(row_cmd[5]),
    .A2(_302_),
    .A3(_305_),
    .B1(_307_),
    .B2(\u_bank_manager.active_row_reg[1][5] ),
    .X(_074_)
  );
  sky130_fd_sc_hd__buf_1 _660_ (
    .A(_281_),
    .X(_308_)
  );
  sky130_fd_sc_hd__a32o_2 _661_ (
    .A1(row_cmd[6]),
    .A2(_308_),
    .A3(_305_),
    .B1(_307_),
    .B2(\u_bank_manager.active_row_reg[1][6] ),
    .X(_075_)
  );
  sky130_fd_sc_hd__a32o_2 _662_ (
    .A1(row_cmd[7]),
    .A2(_308_),
    .A3(_305_),
    .B1(_307_),
    .B2(\u_bank_manager.active_row_reg[1][7] ),
    .X(_076_)
  );
  sky130_fd_sc_hd__a32o_2 _663_ (
    .A1(row_cmd[8]),
    .A2(_308_),
    .A3(_305_),
    .B1(_307_),
    .B2(\u_bank_manager.active_row_reg[1][8] ),
    .X(_077_)
  );
  sky130_fd_sc_hd__a32o_2 _664_ (
    .A1(row_cmd[9]),
    .A2(_308_),
    .A3(_305_),
    .B1(_307_),
    .B2(\u_bank_manager.active_row_reg[1][9] ),
    .X(_078_)
  );
  sky130_fd_sc_hd__a32o_2 _665_ (
    .A1(row_cmd[10]),
    .A2(_308_),
    .A3(_304_),
    .B1(_306_),
    .B2(\u_bank_manager.active_row_reg[1][10] ),
    .X(_079_)
  );
  sky130_fd_sc_hd__a32o_2 _666_ (
    .A1(row_cmd[11]),
    .A2(_308_),
    .A3(_304_),
    .B1(_306_),
    .B2(\u_bank_manager.active_row_reg[1][11] ),
    .X(_080_)
  );
  sky130_fd_sc_hd__and3_2 _667_ (
    .A(\u_bank_manager.query_bank[1] ),
    .B(\u_bank_manager.query_bank[0] ),
    .C(_169_),
    .X(_309_)
  );
  sky130_fd_sc_hd__buf_1 _668_ (
    .A(_309_),
    .X(_310_)
  );
  sky130_fd_sc_hd__buf_1 _669_ (
    .A(_310_),
    .X(_311_)
  );
  sky130_fd_sc_hd__a21oi_2 _670_ (
    .A1(_280_),
    .A2(_310_),
    .B1(reset),
    .Y(_312_)
  );
  sky130_fd_sc_hd__buf_1 _671_ (
    .A(_312_),
    .X(_313_)
  );
  sky130_fd_sc_hd__a32o_2 _672_ (
    .A1(row_cmd[0]),
    .A2(_308_),
    .A3(_311_),
    .B1(_313_),
    .B2(\u_bank_manager.active_row_reg[3][0] ),
    .X(_081_)
  );
  sky130_fd_sc_hd__a32o_2 _673_ (
    .A1(row_cmd[1]),
    .A2(_308_),
    .A3(_311_),
    .B1(_313_),
    .B2(\u_bank_manager.active_row_reg[3][1] ),
    .X(_082_)
  );
  sky130_fd_sc_hd__a32o_2 _674_ (
    .A1(row_cmd[2]),
    .A2(_308_),
    .A3(_311_),
    .B1(_313_),
    .B2(\u_bank_manager.active_row_reg[3][2] ),
    .X(_083_)
  );
  sky130_fd_sc_hd__a32o_2 _675_ (
    .A1(row_cmd[3]),
    .A2(_308_),
    .A3(_311_),
    .B1(_313_),
    .B2(\u_bank_manager.active_row_reg[3][3] ),
    .X(_084_)
  );
  sky130_fd_sc_hd__a32o_2 _676_ (
    .A1(row_cmd[4]),
    .A2(_282_),
    .A3(_311_),
    .B1(_313_),
    .B2(\u_bank_manager.active_row_reg[3][4] ),
    .X(_085_)
  );
  sky130_fd_sc_hd__a32o_2 _677_ (
    .A1(row_cmd[5]),
    .A2(_282_),
    .A3(_311_),
    .B1(_313_),
    .B2(\u_bank_manager.active_row_reg[3][5] ),
    .X(_086_)
  );
  sky130_fd_sc_hd__a32o_2 _678_ (
    .A1(row_cmd[6]),
    .A2(_282_),
    .A3(_311_),
    .B1(_313_),
    .B2(\u_bank_manager.active_row_reg[3][6] ),
    .X(_087_)
  );
  sky130_fd_sc_hd__a32o_2 _679_ (
    .A1(row_cmd[7]),
    .A2(_282_),
    .A3(_311_),
    .B1(_313_),
    .B2(\u_bank_manager.active_row_reg[3][7] ),
    .X(_088_)
  );
  sky130_fd_sc_hd__a32o_2 _680_ (
    .A1(row_cmd[8]),
    .A2(_282_),
    .A3(_311_),
    .B1(_313_),
    .B2(\u_bank_manager.active_row_reg[3][8] ),
    .X(_089_)
  );
  sky130_fd_sc_hd__a32o_2 _681_ (
    .A1(row_cmd[9]),
    .A2(_282_),
    .A3(_311_),
    .B1(_313_),
    .B2(\u_bank_manager.active_row_reg[3][9] ),
    .X(_090_)
  );
  sky130_fd_sc_hd__a32o_2 _682_ (
    .A1(row_cmd[10]),
    .A2(_282_),
    .A3(_310_),
    .B1(_312_),
    .B2(\u_bank_manager.active_row_reg[3][10] ),
    .X(_091_)
  );
  sky130_fd_sc_hd__a32o_2 _683_ (
    .A1(row_cmd[11]),
    .A2(_282_),
    .A3(_310_),
    .B1(_312_),
    .B2(\u_bank_manager.active_row_reg[3][11] ),
    .X(_092_)
  );
  sky130_fd_sc_hd__and2_2 _684_ (
    .A(_160_),
    .B(_271_),
    .X(_314_)
  );
  sky130_fd_sc_hd__buf_1 _685_ (
    .A(_314_),
    .X(_093_)
  );
  sky130_fd_sc_hd__and2_2 _686_ (
    .A(_160_),
    .B(_273_),
    .X(_315_)
  );
  sky130_fd_sc_hd__buf_1 _687_ (
    .A(_315_),
    .X(_094_)
  );
  sky130_fd_sc_hd__a21oi_2 _688_ (
    .A1(_216_),
    .A2(\u_sdram_init.state[0] ),
    .B1(_291_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__or3b_2 _689_ (
    .A(_294_),
    .B(_295_),
    .C_N(_316_),
    .X(_317_)
  );
  sky130_fd_sc_hd__a211o_2 _690_ (
    .A1(_216_),
    .A2(_212_),
    .B1(_316_),
    .C1(_211_),
    .X(_318_)
  );
  sky130_fd_sc_hd__or3b_2 _691_ (
    .A(_212_),
    .B(_291_),
    .C_N(_216_),
    .X(_319_)
  );
  sky130_fd_sc_hd__a31o_2 _692_ (
    .A1(_317_),
    .A2(_318_),
    .A3(_319_),
    .B1(_151_),
    .X(_095_)
  );
  sky130_fd_sc_hd__xor2_2 _693_ (
    .A(\u_sdram_init.delay_counter[1] ),
    .B(\u_sdram_init.delay_counter[0] ),
    .X(_320_)
  );
  sky130_fd_sc_hd__a211o_2 _694_ (
    .A1(_216_),
    .A2(_212_),
    .B1(_316_),
    .C1(_320_),
    .X(_321_)
  );
  sky130_fd_sc_hd__a21o_2 _695_ (
    .A1(init_done),
    .A2(_288_),
    .B1(_150_),
    .X(_322_)
  );
  sky130_fd_sc_hd__a21oi_2 _696_ (
    .A1(_317_),
    .A2(_321_),
    .B1(_322_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__or3_2 _697_ (
    .A(\u_sdram_init.delay_counter[2] ),
    .B(\u_sdram_init.delay_counter[1] ),
    .C(\u_sdram_init.delay_counter[0] ),
    .X(_323_)
  );
  sky130_fd_sc_hd__o21ai_2 _698_ (
    .A1(\u_sdram_init.delay_counter[1] ),
    .A2(\u_sdram_init.delay_counter[0] ),
    .B1(\u_sdram_init.delay_counter[2] ),
    .Y(_324_)
  );
  sky130_fd_sc_hd__a221o_2 _699_ (
    .A1(_216_),
    .A2(_212_),
    .B1(_323_),
    .B2(_324_),
    .C1(_316_),
    .X(_325_)
  );
  sky130_fd_sc_hd__a21oi_2 _700_ (
    .A1(_317_),
    .A2(_325_),
    .B1(_322_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a21o_2 _701_ (
    .A1(_216_),
    .A2(_212_),
    .B1(reset),
    .X(_326_)
  );
  sky130_fd_sc_hd__a21oi_2 _702_ (
    .A1(_209_),
    .A2(_210_),
    .B1(_290_),
    .Y(_327_)
  );
  sky130_fd_sc_hd__a211o_2 _703_ (
    .A1(\u_sdram_init.delay_counter[3] ),
    .A2(_323_),
    .B1(_326_),
    .C1(_327_),
    .X(_098_)
  );
  sky130_fd_sc_hd__or2_2 _704_ (
    .A(_326_),
    .B(_316_),
    .X(_328_)
  );
  sky130_fd_sc_hd__buf_1 _705_ (
    .A(_328_),
    .X(_329_)
  );
  sky130_fd_sc_hd__a211oi_2 _706_ (
    .A1(_209_),
    .A2(_210_),
    .B1(_290_),
    .C1(\u_sdram_init.delay_counter[4] ),
    .Y(_330_)
  );
  sky130_fd_sc_hd__a21oi_2 _707_ (
    .A1(\u_sdram_init.delay_counter[4] ),
    .A2(_290_),
    .B1(_330_),
    .Y(_331_)
  );
  sky130_fd_sc_hd__nor2_2 _708_ (
    .A(_329_),
    .B(_331_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__xnor2_2 _709_ (
    .A(\u_sdram_init.delay_counter[5] ),
    .B(_330_),
    .Y(_332_)
  );
  sky130_fd_sc_hd__nor2_2 _710_ (
    .A(_329_),
    .B(_332_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o31ai_2 _711_ (
    .A1(\u_sdram_init.delay_counter[5] ),
    .A2(\u_sdram_init.delay_counter[4] ),
    .A3(_290_),
    .B1(\u_sdram_init.delay_counter[6] ),
    .Y(_333_)
  );
  sky130_fd_sc_hd__or2_2 _712_ (
    .A(\u_sdram_init.delay_counter[6] ),
    .B(\u_sdram_init.delay_counter[5] ),
    .X(_334_)
  );
  sky130_fd_sc_hd__or2b_2 _713_ (
    .A(_334_),
    .B_N(_330_),
    .X(_335_)
  );
  sky130_fd_sc_hd__a21oi_2 _714_ (
    .A1(_333_),
    .A2(_335_),
    .B1(_329_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o31a_2 _715_ (
    .A1(\u_sdram_init.delay_counter[4] ),
    .A2(_334_),
    .A3(_290_),
    .B1(\u_sdram_init.delay_counter[7] ),
    .X(_336_)
  );
  sky130_fd_sc_hd__o211a_2 _716_ (
    .A1(_162_),
    .A2(_163_),
    .B1(_210_),
    .C1(_287_),
    .X(_337_)
  );
  sky130_fd_sc_hd__o21ba_2 _717_ (
    .A1(_336_),
    .A2(_337_),
    .B1_N(_329_),
    .X(_102_)
  );
  sky130_fd_sc_hd__inv_2 _718_ (
    .A(\u_sdram_init.delay_counter[8] ),
    .Y(_338_)
  );
  sky130_fd_sc_hd__o2111ai_2 _719_ (
    .A1(_162_),
    .A2(_163_),
    .B1(_210_),
    .C1(_287_),
    .D1(_338_),
    .Y(_339_)
  );
  sky130_fd_sc_hd__or2_2 _720_ (
    .A(_338_),
    .B(_337_),
    .X(_340_)
  );
  sky130_fd_sc_hd__a21oi_2 _721_ (
    .A1(_339_),
    .A2(_340_),
    .B1(_329_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_2 _722_ (
    .A(\u_sdram_init.delay_counter[9] ),
    .B(_339_),
    .Y(_341_)
  );
  sky130_fd_sc_hd__or2_2 _723_ (
    .A(\u_sdram_init.delay_counter[9] ),
    .B(_339_),
    .X(_342_)
  );
  sky130_fd_sc_hd__a21oi_2 _724_ (
    .A1(_341_),
    .A2(_342_),
    .B1(_329_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21ai_2 _725_ (
    .A1(\u_sdram_init.delay_counter[9] ),
    .A2(_339_),
    .B1(\u_sdram_init.delay_counter[10] ),
    .Y(_343_)
  );
  sky130_fd_sc_hd__or3_2 _726_ (
    .A(\u_sdram_init.delay_counter[10] ),
    .B(\u_sdram_init.delay_counter[9] ),
    .C(_339_),
    .X(_344_)
  );
  sky130_fd_sc_hd__a21oi_2 _727_ (
    .A1(_343_),
    .A2(_344_),
    .B1(_329_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xor2_2 _728_ (
    .A(\u_sdram_init.delay_counter[11] ),
    .B(_344_),
    .X(_345_)
  );
  sky130_fd_sc_hd__nor2_2 _729_ (
    .A(_329_),
    .B(_345_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__o21a_2 _730_ (
    .A1(\u_sdram_init.delay_counter[11] ),
    .A2(_344_),
    .B1(\u_sdram_init.delay_counter[12] ),
    .X(_346_)
  );
  sky130_fd_sc_hd__or2_2 _731_ (
    .A(\u_sdram_init.delay_counter[12] ),
    .B(\u_sdram_init.delay_counter[11] ),
    .X(_347_)
  );
  sky130_fd_sc_hd__or4_2 _732_ (
    .A(\u_sdram_init.delay_counter[10] ),
    .B(\u_sdram_init.delay_counter[9] ),
    .C(_347_),
    .D(_339_),
    .X(_348_)
  );
  sky130_fd_sc_hd__inv_2 _733_ (
    .A(_348_),
    .Y(_349_)
  );
  sky130_fd_sc_hd__o21ba_2 _734_ (
    .A1(_346_),
    .A2(_349_),
    .B1_N(_329_),
    .X(_107_)
  );
  sky130_fd_sc_hd__nand2_2 _735_ (
    .A(\u_sdram_init.delay_counter[13] ),
    .B(_348_),
    .Y(_350_)
  );
  sky130_fd_sc_hd__or2_2 _736_ (
    .A(\u_sdram_init.delay_counter[13] ),
    .B(_348_),
    .X(_351_)
  );
  sky130_fd_sc_hd__a21oi_2 _737_ (
    .A1(_350_),
    .A2(_351_),
    .B1(_329_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o21ai_2 _738_ (
    .A1(\u_sdram_init.delay_counter[13] ),
    .A2(_348_),
    .B1(\u_sdram_init.delay_counter[14] ),
    .Y(_352_)
  );
  sky130_fd_sc_hd__or3_2 _739_ (
    .A(\u_sdram_init.delay_counter[14] ),
    .B(\u_sdram_init.delay_counter[13] ),
    .C(_348_),
    .X(_353_)
  );
  sky130_fd_sc_hd__a21oi_2 _740_ (
    .A1(_352_),
    .A2(_353_),
    .B1(_328_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__and4b_2 _741_ (
    .A_N(_316_),
    .B(_353_),
    .C(\u_sdram_init.delay_counter[15] ),
    .D(_293_),
    .X(_354_)
  );
  sky130_fd_sc_hd__buf_1 _742_ (
    .A(_354_),
    .X(_110_)
  );
  sky130_fd_sc_hd__nor2_2 _743_ (
    .A(_150_),
    .B(precharge_all_cmd),
    .Y(_355_)
  );
  sky130_fd_sc_hd__a31o_2 _744_ (
    .A1(\u_bank_manager.query_bank[1] ),
    .A2(\u_bank_manager.query_bank[0] ),
    .A3(_154_),
    .B1(\u_bank_manager.bank_open_reg[3] ),
    .X(_356_)
  );
  sky130_fd_sc_hd__nand2_2 _745_ (
    .A(precharge_cmd),
    .B(_310_),
    .Y(_357_)
  );
  sky130_fd_sc_hd__and3_2 _746_ (
    .A(_355_),
    .B(_356_),
    .C(_357_),
    .X(_358_)
  );
  sky130_fd_sc_hd__buf_1 _747_ (
    .A(_358_),
    .X(_111_)
  );
  sky130_fd_sc_hd__or2_2 _748_ (
    .A(_150_),
    .B(precharge_all_cmd),
    .X(_359_)
  );
  sky130_fd_sc_hd__a21oi_2 _749_ (
    .A1(_154_),
    .A2(_298_),
    .B1(\u_bank_manager.bank_open_reg[2] ),
    .Y(_360_)
  );
  sky130_fd_sc_hd__a211oi_2 _750_ (
    .A1(precharge_cmd),
    .A2(_298_),
    .B1(_359_),
    .C1(_360_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21oi_2 _751_ (
    .A1(_154_),
    .A2(_304_),
    .B1(\u_bank_manager.bank_open_reg[1] ),
    .Y(_361_)
  );
  sky130_fd_sc_hd__a211oi_2 _752_ (
    .A1(precharge_cmd),
    .A2(_304_),
    .B1(_359_),
    .C1(_361_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a21o_2 _753_ (
    .A1(_154_),
    .A2(_278_),
    .B1(\u_bank_manager.bank_open_reg[0] ),
    .X(_362_)
  );
  sky130_fd_sc_hd__o311a_2 _754_ (
    .A1(\u_bank_manager.query_bank[1] ),
    .A2(\u_bank_manager.query_bank[0] ),
    .A3(_275_),
    .B1(_355_),
    .C1(_362_),
    .X(_114_)
  );
  sky130_fd_sc_hd__dfxtp_2 _755_ (
    .CLK(clk),
    .D(_014_),
    .Q(\u_command_generator.delay_counter[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _756_ (
    .CLK(clk),
    .D(_015_),
    .Q(\u_command_generator.delay_counter[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _757_ (
    .CLK(clk),
    .D(_016_),
    .Q(\u_command_generator.delay_counter[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _758_ (
    .CLK(clk),
    .D(_017_),
    .Q(\u_command_generator.precharge_for_miss )
  );
  sky130_fd_sc_hd__dfxtp_2 _759_ (
    .CLK(clk),
    .D(_018_),
    .Q(\u_command_generator.req_pending )
  );
  sky130_fd_sc_hd__dfxtp_2 _760_ (
    .CLK(clk),
    .D(_019_),
    .Q(\u_command_generator.request_column_reg[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _761_ (
    .CLK(clk),
    .D(_020_),
    .Q(\u_command_generator.request_column_reg[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _762_ (
    .CLK(clk),
    .D(_021_),
    .Q(\u_command_generator.request_column_reg[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _763_ (
    .CLK(clk),
    .D(_022_),
    .Q(\u_command_generator.request_column_reg[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _764_ (
    .CLK(clk),
    .D(_023_),
    .Q(\u_command_generator.request_column_reg[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _765_ (
    .CLK(clk),
    .D(_024_),
    .Q(\u_command_generator.request_column_reg[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _766_ (
    .CLK(clk),
    .D(_025_),
    .Q(\u_command_generator.request_column_reg[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _767_ (
    .CLK(clk),
    .D(_026_),
    .Q(\u_command_generator.request_column_reg[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _768_ (
    .CLK(clk),
    .D(_027_),
    .Q(\u_command_generator.request_row_reg[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _769_ (
    .CLK(clk),
    .D(_028_),
    .Q(\u_command_generator.request_row_reg[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _770_ (
    .CLK(clk),
    .D(_029_),
    .Q(\u_command_generator.request_row_reg[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _771_ (
    .CLK(clk),
    .D(_030_),
    .Q(\u_command_generator.request_row_reg[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _772_ (
    .CLK(clk),
    .D(_031_),
    .Q(\u_command_generator.request_row_reg[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _773_ (
    .CLK(clk),
    .D(_032_),
    .Q(\u_command_generator.request_row_reg[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _774_ (
    .CLK(clk),
    .D(_033_),
    .Q(\u_command_generator.request_row_reg[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _775_ (
    .CLK(clk),
    .D(_034_),
    .Q(\u_command_generator.request_row_reg[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _776_ (
    .CLK(clk),
    .D(_035_),
    .Q(\u_command_generator.request_row_reg[8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _777_ (
    .CLK(clk),
    .D(_036_),
    .Q(\u_command_generator.request_row_reg[9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _778_ (
    .CLK(clk),
    .D(_037_),
    .Q(\u_command_generator.request_row_reg[10] )
  );
  sky130_fd_sc_hd__dfxtp_2 _779_ (
    .CLK(clk),
    .D(_038_),
    .Q(\u_command_generator.request_row_reg[11] )
  );
  sky130_fd_sc_hd__dfxtp_2 _780_ (
    .CLK(clk),
    .D(_039_),
    .Q(\u_bank_manager.query_bank[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _781_ (
    .CLK(clk),
    .D(_040_),
    .Q(\u_bank_manager.query_bank[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _782_ (
    .CLK(clk),
    .D(_041_),
    .Q(\u_command_generator.delay_counter[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _783_ (
    .CLK(clk),
    .D(_011_),
    .Q(_363_)
  );
  sky130_fd_sc_hd__dfxtp_2 _784_ (
    .CLK(clk),
    .D(_012_),
    .Q(_364_)
  );
  sky130_fd_sc_hd__dfxtp_2 _785_ (
    .CLK(clk),
    .D(_013_),
    .Q(_365_)
  );
  sky130_fd_sc_hd__dfxtp_2 _786_ (
    .CLK(clk),
    .D(_042_),
    .Q(\u_bank_manager.active_row_reg[0][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _787_ (
    .CLK(clk),
    .D(_043_),
    .Q(\u_bank_manager.active_row_reg[0][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _788_ (
    .CLK(clk),
    .D(_044_),
    .Q(\u_bank_manager.active_row_reg[0][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _789_ (
    .CLK(clk),
    .D(_045_),
    .Q(\u_bank_manager.active_row_reg[0][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _790_ (
    .CLK(clk),
    .D(_046_),
    .Q(\u_bank_manager.active_row_reg[0][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _791_ (
    .CLK(clk),
    .D(_047_),
    .Q(\u_bank_manager.active_row_reg[0][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _792_ (
    .CLK(clk),
    .D(_048_),
    .Q(\u_bank_manager.active_row_reg[0][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _793_ (
    .CLK(clk),
    .D(_049_),
    .Q(\u_bank_manager.active_row_reg[0][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _794_ (
    .CLK(clk),
    .D(_050_),
    .Q(\u_bank_manager.active_row_reg[0][8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _795_ (
    .CLK(clk),
    .D(_051_),
    .Q(\u_bank_manager.active_row_reg[0][9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _796_ (
    .CLK(clk),
    .D(_052_),
    .Q(\u_bank_manager.active_row_reg[0][10] )
  );
  sky130_fd_sc_hd__dfxtp_2 _797_ (
    .CLK(clk),
    .D(_053_),
    .Q(\u_bank_manager.active_row_reg[0][11] )
  );
  sky130_fd_sc_hd__dfxtp_2 _798_ (
    .CLK(clk),
    .D(_054_),
    .Q(\u_sdram_init.state[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _799_ (
    .CLK(clk),
    .D(_055_),
    .Q(\u_sdram_init.state[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _800_ (
    .CLK(clk),
    .D(_056_),
    .Q(\u_sdram_init.state[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _801_ (
    .CLK(clk),
    .D(_004_),
    .Q(\u_command_generator.state[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _802_ (
    .CLK(clk),
    .D(_005_),
    .Q(\u_command_generator.state[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _803_ (
    .CLK(clk),
    .D(_006_),
    .Q(read_cmd)
  );
  sky130_fd_sc_hd__dfxtp_2 _804_ (
    .CLK(clk),
    .D(_007_),
    .Q(activate_cmd)
  );
  sky130_fd_sc_hd__dfxtp_2 _805_ (
    .CLK(clk),
    .D(_002_),
    .Q(data_valid)
  );
  sky130_fd_sc_hd__dfxtp_2 _806_ (
    .CLK(clk),
    .D(_003_),
    .Q(\u_command_generator.state[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _807_ (
    .CLK(clk),
    .D(_008_),
    .Q(\u_command_generator.state[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _808_ (
    .CLK(clk),
    .D(_009_),
    .Q(\u_command_generator.state[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _809_ (
    .CLK(clk),
    .D(_010_),
    .Q(precharge_cmd)
  );
  sky130_fd_sc_hd__dfxtp_2 _810_ (
    .CLK(clk),
    .D(_057_),
    .Q(\u_bank_manager.active_row_reg[2][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _811_ (
    .CLK(clk),
    .D(_058_),
    .Q(\u_bank_manager.active_row_reg[2][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _812_ (
    .CLK(clk),
    .D(_059_),
    .Q(\u_bank_manager.active_row_reg[2][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _813_ (
    .CLK(clk),
    .D(_060_),
    .Q(\u_bank_manager.active_row_reg[2][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _814_ (
    .CLK(clk),
    .D(_061_),
    .Q(\u_bank_manager.active_row_reg[2][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _815_ (
    .CLK(clk),
    .D(_062_),
    .Q(\u_bank_manager.active_row_reg[2][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _816_ (
    .CLK(clk),
    .D(_063_),
    .Q(\u_bank_manager.active_row_reg[2][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _817_ (
    .CLK(clk),
    .D(_064_),
    .Q(\u_bank_manager.active_row_reg[2][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _818_ (
    .CLK(clk),
    .D(_065_),
    .Q(\u_bank_manager.active_row_reg[2][8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _819_ (
    .CLK(clk),
    .D(_066_),
    .Q(\u_bank_manager.active_row_reg[2][9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _820_ (
    .CLK(clk),
    .D(_067_),
    .Q(\u_bank_manager.active_row_reg[2][10] )
  );
  sky130_fd_sc_hd__dfxtp_2 _821_ (
    .CLK(clk),
    .D(_068_),
    .Q(\u_bank_manager.active_row_reg[2][11] )
  );
  sky130_fd_sc_hd__dfxtp_2 _822_ (
    .CLK(clk),
    .D(_069_),
    .Q(\u_bank_manager.active_row_reg[1][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _823_ (
    .CLK(clk),
    .D(_070_),
    .Q(\u_bank_manager.active_row_reg[1][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _824_ (
    .CLK(clk),
    .D(_071_),
    .Q(\u_bank_manager.active_row_reg[1][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _825_ (
    .CLK(clk),
    .D(_072_),
    .Q(\u_bank_manager.active_row_reg[1][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _826_ (
    .CLK(clk),
    .D(_073_),
    .Q(\u_bank_manager.active_row_reg[1][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _827_ (
    .CLK(clk),
    .D(_074_),
    .Q(\u_bank_manager.active_row_reg[1][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _828_ (
    .CLK(clk),
    .D(_075_),
    .Q(\u_bank_manager.active_row_reg[1][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _829_ (
    .CLK(clk),
    .D(_076_),
    .Q(\u_bank_manager.active_row_reg[1][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _830_ (
    .CLK(clk),
    .D(_077_),
    .Q(\u_bank_manager.active_row_reg[1][8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _831_ (
    .CLK(clk),
    .D(_078_),
    .Q(\u_bank_manager.active_row_reg[1][9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _832_ (
    .CLK(clk),
    .D(_079_),
    .Q(\u_bank_manager.active_row_reg[1][10] )
  );
  sky130_fd_sc_hd__dfxtp_2 _833_ (
    .CLK(clk),
    .D(_080_),
    .Q(\u_bank_manager.active_row_reg[1][11] )
  );
  sky130_fd_sc_hd__dfxtp_2 _834_ (
    .CLK(clk),
    .D(_081_),
    .Q(\u_bank_manager.active_row_reg[3][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _835_ (
    .CLK(clk),
    .D(_082_),
    .Q(\u_bank_manager.active_row_reg[3][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _836_ (
    .CLK(clk),
    .D(_083_),
    .Q(\u_bank_manager.active_row_reg[3][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _837_ (
    .CLK(clk),
    .D(_084_),
    .Q(\u_bank_manager.active_row_reg[3][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _838_ (
    .CLK(clk),
    .D(_085_),
    .Q(\u_bank_manager.active_row_reg[3][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _839_ (
    .CLK(clk),
    .D(_086_),
    .Q(\u_bank_manager.active_row_reg[3][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _840_ (
    .CLK(clk),
    .D(_087_),
    .Q(\u_bank_manager.active_row_reg[3][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _841_ (
    .CLK(clk),
    .D(_088_),
    .Q(\u_bank_manager.active_row_reg[3][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _842_ (
    .CLK(clk),
    .D(_089_),
    .Q(\u_bank_manager.active_row_reg[3][8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _843_ (
    .CLK(clk),
    .D(_090_),
    .Q(\u_bank_manager.active_row_reg[3][9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _844_ (
    .CLK(clk),
    .D(_091_),
    .Q(\u_bank_manager.active_row_reg[3][10] )
  );
  sky130_fd_sc_hd__dfxtp_2 _845_ (
    .CLK(clk),
    .D(_092_),
    .Q(\u_bank_manager.active_row_reg[3][11] )
  );
  sky130_fd_sc_hd__dfxtp_2 _846_ (
    .CLK(clk),
    .D(_093_),
    .Q(_000_)
  );
  sky130_fd_sc_hd__dfxtp_2 _847_ (
    .CLK(clk),
    .D(_094_),
    .Q(_001_)
  );
  sky130_fd_sc_hd__dfxtp_2 _848_ (
    .CLK(clk),
    .D(_095_),
    .Q(\u_sdram_init.delay_counter[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _849_ (
    .CLK(clk),
    .D(_096_),
    .Q(\u_sdram_init.delay_counter[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _850_ (
    .CLK(clk),
    .D(_097_),
    .Q(\u_sdram_init.delay_counter[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _851_ (
    .CLK(clk),
    .D(_098_),
    .Q(\u_sdram_init.delay_counter[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _852_ (
    .CLK(clk),
    .D(_099_),
    .Q(\u_sdram_init.delay_counter[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _853_ (
    .CLK(clk),
    .D(_100_),
    .Q(\u_sdram_init.delay_counter[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _854_ (
    .CLK(clk),
    .D(_101_),
    .Q(\u_sdram_init.delay_counter[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _855_ (
    .CLK(clk),
    .D(_102_),
    .Q(\u_sdram_init.delay_counter[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _856_ (
    .CLK(clk),
    .D(_103_),
    .Q(\u_sdram_init.delay_counter[8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _857_ (
    .CLK(clk),
    .D(_104_),
    .Q(\u_sdram_init.delay_counter[9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _858_ (
    .CLK(clk),
    .D(_105_),
    .Q(\u_sdram_init.delay_counter[10] )
  );
  sky130_fd_sc_hd__dfxtp_2 _859_ (
    .CLK(clk),
    .D(_106_),
    .Q(\u_sdram_init.delay_counter[11] )
  );
  sky130_fd_sc_hd__dfxtp_2 _860_ (
    .CLK(clk),
    .D(_107_),
    .Q(\u_sdram_init.delay_counter[12] )
  );
  sky130_fd_sc_hd__dfxtp_2 _861_ (
    .CLK(clk),
    .D(_108_),
    .Q(\u_sdram_init.delay_counter[13] )
  );
  sky130_fd_sc_hd__dfxtp_2 _862_ (
    .CLK(clk),
    .D(_109_),
    .Q(\u_sdram_init.delay_counter[14] )
  );
  sky130_fd_sc_hd__dfxtp_2 _863_ (
    .CLK(clk),
    .D(_110_),
    .Q(\u_sdram_init.delay_counter[15] )
  );
  sky130_fd_sc_hd__dfxtp_2 _864_ (
    .CLK(clk),
    .D(_111_),
    .Q(\u_bank_manager.bank_open_reg[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _865_ (
    .CLK(clk),
    .D(_112_),
    .Q(\u_bank_manager.bank_open_reg[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _866_ (
    .CLK(clk),
    .D(_113_),
    .Q(\u_bank_manager.bank_open_reg[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _867_ (
    .CLK(clk),
    .D(_114_),
    .Q(\u_bank_manager.bank_open_reg[0] )
  );
  sky130_fd_sc_hd__conb_1 _868_ (
    .LO(read_data[4])
  );
  sky130_fd_sc_hd__conb_1 _869_ (
    .LO(read_data[8])
  );
  sky130_fd_sc_hd__conb_1 _870_ (
    .LO(read_data[14])
  );
  sky130_fd_sc_hd__conb_1 _871_ (
    .LO(read_data[17])
  );
  sky130_fd_sc_hd__conb_1 _872_ (
    .LO(read_data[20])
  );
  sky130_fd_sc_hd__conb_1 _873_ (
    .LO(read_data[22])
  );
  sky130_fd_sc_hd__conb_1 _874_ (
    .LO(read_data[24])
  );
  sky130_fd_sc_hd__conb_1 _875_ (
    .LO(read_data[29])
  );
  sky130_fd_sc_hd__buf_2 _876_ (
    .A(data_valid),
    .X(read_data[0])
  );
  sky130_fd_sc_hd__buf_2 _877_ (
    .A(data_valid),
    .X(read_data[1])
  );
  sky130_fd_sc_hd__buf_2 _878_ (
    .A(data_valid),
    .X(read_data[2])
  );
  sky130_fd_sc_hd__buf_2 _879_ (
    .A(data_valid),
    .X(read_data[3])
  );
  sky130_fd_sc_hd__buf_2 _880_ (
    .A(data_valid),
    .X(read_data[5])
  );
  sky130_fd_sc_hd__buf_2 _881_ (
    .A(data_valid),
    .X(read_data[6])
  );
  sky130_fd_sc_hd__buf_2 _882_ (
    .A(data_valid),
    .X(read_data[7])
  );
  sky130_fd_sc_hd__buf_2 _883_ (
    .A(data_valid),
    .X(read_data[9])
  );
  sky130_fd_sc_hd__buf_2 _884_ (
    .A(data_valid),
    .X(read_data[10])
  );
  sky130_fd_sc_hd__buf_2 _885_ (
    .A(data_valid),
    .X(read_data[11])
  );
  sky130_fd_sc_hd__buf_2 _886_ (
    .A(data_valid),
    .X(read_data[12])
  );
  sky130_fd_sc_hd__buf_2 _887_ (
    .A(data_valid),
    .X(read_data[13])
  );
  sky130_fd_sc_hd__buf_2 _888_ (
    .A(data_valid),
    .X(read_data[15])
  );
  sky130_fd_sc_hd__buf_2 _889_ (
    .A(data_valid),
    .X(read_data[16])
  );
  sky130_fd_sc_hd__buf_2 _890_ (
    .A(data_valid),
    .X(read_data[18])
  );
  sky130_fd_sc_hd__buf_2 _891_ (
    .A(data_valid),
    .X(read_data[19])
  );
  sky130_fd_sc_hd__buf_2 _892_ (
    .A(data_valid),
    .X(read_data[21])
  );
  sky130_fd_sc_hd__buf_2 _893_ (
    .A(data_valid),
    .X(read_data[23])
  );
  sky130_fd_sc_hd__buf_2 _894_ (
    .A(data_valid),
    .X(read_data[25])
  );
  sky130_fd_sc_hd__buf_2 _895_ (
    .A(data_valid),
    .X(read_data[26])
  );
  sky130_fd_sc_hd__buf_2 _896_ (
    .A(data_valid),
    .X(read_data[27])
  );
  sky130_fd_sc_hd__buf_2 _897_ (
    .A(data_valid),
    .X(read_data[28])
  );
  sky130_fd_sc_hd__buf_2 _898_ (
    .A(data_valid),
    .X(read_data[30])
  );
  sky130_fd_sc_hd__buf_2 _899_ (
    .A(data_valid),
    .X(read_data[31])
  );
endmodule
