###############################################################################
# Created by write_sdc
# Tue Jul 28 15:40:14 2026
###############################################################################
current_design sdram_controller
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 10.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {address[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_request}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reset}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {activate_cmd}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bank_cmd[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bank_cmd[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {column_cmd[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {column_cmd[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {column_cmd[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {column_cmd[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {column_cmd[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {column_cmd[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {column_cmd[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {column_cmd[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data_valid}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {init_done}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {load_mode_cmd}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {precharge_all_cmd}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {precharge_cmd}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_cmd}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ready}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {refresh_cmd}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {req_ack}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {row_cmd[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {activate_cmd}]
set_load -pin_load 0.0334 [get_ports {data_valid}]
set_load -pin_load 0.0334 [get_ports {init_done}]
set_load -pin_load 0.0334 [get_ports {load_mode_cmd}]
set_load -pin_load 0.0334 [get_ports {precharge_all_cmd}]
set_load -pin_load 0.0334 [get_ports {precharge_cmd}]
set_load -pin_load 0.0334 [get_ports {read_cmd}]
set_load -pin_load 0.0334 [get_ports {ready}]
set_load -pin_load 0.0334 [get_ports {refresh_cmd}]
set_load -pin_load 0.0334 [get_ports {req_ack}]
set_load -pin_load 0.0334 [get_ports {bank_cmd[1]}]
set_load -pin_load 0.0334 [get_ports {bank_cmd[0]}]
set_load -pin_load 0.0334 [get_ports {column_cmd[7]}]
set_load -pin_load 0.0334 [get_ports {column_cmd[6]}]
set_load -pin_load 0.0334 [get_ports {column_cmd[5]}]
set_load -pin_load 0.0334 [get_ports {column_cmd[4]}]
set_load -pin_load 0.0334 [get_ports {column_cmd[3]}]
set_load -pin_load 0.0334 [get_ports {column_cmd[2]}]
set_load -pin_load 0.0334 [get_ports {column_cmd[1]}]
set_load -pin_load 0.0334 [get_ports {column_cmd[0]}]
set_load -pin_load 0.0334 [get_ports {read_data[31]}]
set_load -pin_load 0.0334 [get_ports {read_data[30]}]
set_load -pin_load 0.0334 [get_ports {read_data[29]}]
set_load -pin_load 0.0334 [get_ports {read_data[28]}]
set_load -pin_load 0.0334 [get_ports {read_data[27]}]
set_load -pin_load 0.0334 [get_ports {read_data[26]}]
set_load -pin_load 0.0334 [get_ports {read_data[25]}]
set_load -pin_load 0.0334 [get_ports {read_data[24]}]
set_load -pin_load 0.0334 [get_ports {read_data[23]}]
set_load -pin_load 0.0334 [get_ports {read_data[22]}]
set_load -pin_load 0.0334 [get_ports {read_data[21]}]
set_load -pin_load 0.0334 [get_ports {read_data[20]}]
set_load -pin_load 0.0334 [get_ports {read_data[19]}]
set_load -pin_load 0.0334 [get_ports {read_data[18]}]
set_load -pin_load 0.0334 [get_ports {read_data[17]}]
set_load -pin_load 0.0334 [get_ports {read_data[16]}]
set_load -pin_load 0.0334 [get_ports {read_data[15]}]
set_load -pin_load 0.0334 [get_ports {read_data[14]}]
set_load -pin_load 0.0334 [get_ports {read_data[13]}]
set_load -pin_load 0.0334 [get_ports {read_data[12]}]
set_load -pin_load 0.0334 [get_ports {read_data[11]}]
set_load -pin_load 0.0334 [get_ports {read_data[10]}]
set_load -pin_load 0.0334 [get_ports {read_data[9]}]
set_load -pin_load 0.0334 [get_ports {read_data[8]}]
set_load -pin_load 0.0334 [get_ports {read_data[7]}]
set_load -pin_load 0.0334 [get_ports {read_data[6]}]
set_load -pin_load 0.0334 [get_ports {read_data[5]}]
set_load -pin_load 0.0334 [get_ports {read_data[4]}]
set_load -pin_load 0.0334 [get_ports {read_data[3]}]
set_load -pin_load 0.0334 [get_ports {read_data[2]}]
set_load -pin_load 0.0334 [get_ports {read_data[1]}]
set_load -pin_load 0.0334 [get_ports {read_data[0]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[11]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[10]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[9]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[8]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[7]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[6]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[5]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[4]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[3]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[2]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[1]}]
set_load -pin_load 0.0334 [get_ports {row_cmd[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {read_request}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reset}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {address[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 10.0000 [current_design]
